# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='content',
            field=models.TextField(max_length=240),
        ),
    ]
